[package]
name = "kinesis-db"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
memmap2 = "0.9.5"
rand = "0.9.0"
sha2 = "0.10.8"
base64 = "0.22.1"
parking_lot = "0.12.3"
