[package]
name = "kinesis-db"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
bincode = "1.3.3"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
rand = "0.9.0"
sha2 = "0.10.8"
tabled = "0.18.0"
chrono = "0.4.39"
lazy_static = "1.4.0"
